version: "3.3"

services:
  postgres:
    image: postgres
    container_name: "postgresql"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - net

  django:
    container_name: "django"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - SECRET_KEY='bew9%agaop4^%62ff_v&90ahm2tp8&f%=kap&%q*$$#0but2ef5'
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    ports:
      - 80:8000
    depends_on:
      - postgres
    networks:
      - net
    
networks:
  net:
